### ISSUE TITLE
Page Not Found when tweet has more than 140 characters.

### ISSUE THREAD

**Issue by ktang92** [tobyk100/403-kamal#17]
Need to add a check to see if the tweet is too long.

**Comment by tobyk100** [comment]
What should we do if the user enters a post with more than 140 characters?
1) Not post to twitter.
2) Truncate post to 140 and post to twitter.

We can alert the user with either senario.

**Comment by mengyuanli** [comment]
We could
1) show # of characters entered on the popup if the user have twitter checkbox selected (frontend)
2) then do not post to twitter (backend)

You could assign this task to me if everyone is busy.

**Comment by acetang** [comment]
Meg, can you add a message when user's text has more than 140 chars and has twitter selected. And when that is fixed, I think we can close this issue.

**Comment by mengyuanli** [comment]
No, what I did was to prevent user from adding tweets longer than 140 characters. 

I didn't close this issue because I was hoping to get someone to code review this diff and test the change to make sure I didn't mess up anything.... If everything looks good, feel free to close the issue. :)
