### ISSUE TITLE
[facebook][feed] Page name is not displayed

### ISSUE THREAD

**Issue by mengyuanli** [tobyk100/403-kamal#19]
Repro: load Facebook feeds, notice that the name of page is not displayed.

**Comment by tobyk100** [comment]
Hey Meg, what do you mean the name of the page is not displayed? Which page: facebook or Instafeed?

**Comment by mengyuanli** [comment]
If the Facebook feed is from a friend, everything is fine. 

But if the feed is from a Facebook page, such as Pinterest, the name "Pinterest" is not displayed in the Instafeed feed. Currently on Instafeed page, the feed has `- Sun 15:13:37` instead of `Pinterest - Sun 15:13:37`.
